CREATE DATABASE burgers_db;

USE burgers_db;

CREATE TABLE burgers (
	ID INT(100) AUTO_INCREMENT NOT NULL,
	burger_name VARCHAR(255) NOT NULL,
	devoured BOOLEAN DEFAULT false,
	ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (ID)
);

SELECT * FROM burgers;
